spring:
  application: 
    name: FaceRecGateway
    
server:
  port: 8080
  
ribbon:
  ReadTimeout: 60000

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka

zuul:
  host:
    connect-timeout-millis: 60000
  routes:
    CompareService:
      path: /comp/**
      serviceId: FaceRecService
    S3Service:
      path: /s3/**
      serviceId: FaceRecS3
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin